/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zrrpormwcxzkqfcwtryk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycnBvcm13Y3h6a3FmY3d0cnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3NjI3NzIsImV4cCI6MjA4MTMzODc3Mn0.WzZjSYTZl79dwNmgGibCUh9jKepGgXrO1YP-bLKcvJY"
