### Get all criteria
GET http://localhost:8080/api/criteria

### Create a new Ipa
POST http://localhost:8080/api/ipa
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "topic": "Sample Topic",
  "date": "2024-06-15"
}

### Get IPA by ID
GET http://localhost:8080/api/ipa/AA02

### Get Ipa Criteria by ID
GET http://localhost:8080/api/ipa/AA02/criteria

### Get Ipa personal data by ID
GET http://localhost:8080/api/ipa/AA02/person-data

### Delete IPA by ID
DELETE http://localhost:8080/api/ipa/AA02/criteria/BB03