### Get all criteria
GET http://localhost:8080/api/criteria

### Create a new Ipa
POST http://localhost:8080/api/ipa
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "topic": "Sample Topic",
  "date": "2024-06-15"
}

### Get IPA by ID
GET http://localhost:8080/api/ipa/AA02

### Get Ipa Criteria by ID
GET http://localhost:8080/api/ipa/AA02/criteria

### Add a criterion to IPA
POST http://localhost:8080/api/ipa/AA02/criteria
Content-Type: application/json

{
  "id": "BB03",
  "title": "Test Criterion",
  "question": "Test Description"
}

### Update a criterion of IPA ## TODO BUG: currently doesn't do anything when id doesn't exist
PUT http://localhost:8080/api/ipa/AA02/criteria/BB03
Content-Type: application/json

{
  "id": "BB03",
  "title": "Updated Criterion",
  "question": "Updated Description"
}

### Delete a criterion from IPA
DELETE http://localhost:8080/api/ipa/AA02/criteria/BB03

### Get Ipa personal data by ID
GET http://localhost:8080/api/ipa/AA02/person-data

### Update Ipa personal data by ID
PUT http://localhost:8080/api/ipa/AA02/person-data
Content-Type: application/json

{
  "firstname": "Jane",
  "lastname": "Doe",
  "topic": "Updated Topic",
  "date": "2024-07-01"
}

### Get grade for IPA
GET http://localhost:8080/api/ipa/AA02/grade

